## auth/login
### POST /api/auth/login
POST http://localhost:3000/api/auth/login
content-type: application/json

{"username": "JohnDoe", "password": "to-be-hashed-pw1"}

### GET my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDA2NDQ2MDB9.cN_OM_OQGBN3ldQP0fWhMJVl3Fvm7_rmVz481w2rTr4

### GET /kukkuu
GET http://localhost:3000/kukkuu

### GET /something-else
GET http://localhost:3000/morjes

# Media sharing api http test requests

## /api/media endpoit

### Get all media
GET http://localhost:3000/api/media

### Get media by id
GET http://localhost:3000/api/media/3

### Get media by id FAIL
GET http://localhost:3000/api/media/959099

### Post media 
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6IkpvaG5Eb2UiLCJlbWFpbCI6ImpvaG5kb2VAZXhhbXBsZS5jb20iLCJ1c2VyX2xldmVsX2lkIjoyLCJpYXQiOjE3MDA2NDQ2MDB9.cN_OM_OQGBN3ldQP0fWhMJVl3Fvm7_rmVz481w2rTr4
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="title"

New media title k
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="image.jpg"
Content-Type: image/jpeg

< ./cat.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Post media FAIL
POST http://localhost:3000/api/media
content-type: application/json

{"msg": "HEllo"}

### Update media
PUT http://localhost:3000/api/media/9590
content-type: application/json

{
  "filename": "updated.jpg",
  "title": "Updated Media",
  "description": "updated description",
}

### Update media FAIL
PUT http://localhost:3000/api/media/260
content-type: application/json

{
  "something": "this will fail",
}

### Delete media
DELETE http://localhost:3000/api/media/9590

## /api/users endpoint

### Get all users
GET http://localhost:3000/api/users

### Get user by id
GET http://localhost:3000/api/users/260

### Get user by id FAIL
GET http://localhost:3000/api/users/959099

### Post users 
POST http://localhost:3000/api/users
content-type: application/json

{
  "username": "Newuser",
  "password": "newsecret",
  "email": "newuser@example.com"
}

### Post users FAIL
POST http://localhost:3000/api/users
content-type: application/json

{"msg": "HEllo"}

### Update user
PUT http://localhost:3000/api/users/260
content-type: application/json

{
  "username": "Newuser",
  "password": "newsecret",
  "email": "newuser@example.com"
}

### Update users FAIL
PUT http://localhost:3000/api/users/340
content-type: application/json

{
  "something": "this will fail",
}

### Delete users
DELETE http://localhost:3000/api/users/260
